name: Continuous Integration

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    NO_DOCKER: true
    APP_ENVIRONMENT: test
    DB_HOST: localhost
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    COVERAGE: --coverage-text
    MOCK_HOST: "http://127.0.0.1:8001"
    APP_SUBSCRIPTIONS_HOST: ${{ secrets.APP_SUBSCRIPTIONS_HOST }}
    APP_SUBSCRIPTIONS_PRIVATE_KEY: ${{ secrets.APP_SUBSCRIPTIONS_PRIVATE_KEY }}
    APP_POCKET_CONSUMER_KEY: ${{ secrets.APP_POCKET_CONSUMER_KEY }}

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: [ubuntu-22.04]
                php-versions: ['8.1']

        services:
            postgres:
                image: postgres:13-alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432/tcp
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

        name: PHP ${{ matrix.php-versions }} CI on ${{ matrix.operating-system }}

        steps:
        - uses: actions/checkout@v2
          with:
              submodules: true

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ matrix.php-versions }}
              coverage: xdebug
              extensions: intl, gettext, pcntl, gd, pdo, pdo_pgsql
              ini-values: browscap=${{ github.workspace }}/docker/lite_php_browscap.ini

        - name: Setup locales
          run: |
              sudo apt-get install locales
              sudo locale-gen fr_FR.UTF-8 en_GB.UTF-8

        - name: Get composer cache directory
          id: composer-cache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"

        - name: Cache composer dependencies
          uses: actions/cache@v2
          with:
              path: ${{ steps.composer-cache.outputs.dir }}
              key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
              restore-keys: ${{ runner.os }}-composer-

        - name: Cache node dependencies
          uses: actions/cache@v2
          with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: ${{ runner.os }}-node-

        - name: Install dependencies
          run: make install

        - name: Setup the application
          run: make setup
          env:
              DB_PORT: ${{ job.services.postgres.ports[5432] }}

        - name: Run the linters
          run: make lint

        - name: Run mock_server (background)
          run: php -t ${{ github.workspace }} -S 127.0.0.1:8001 ${{ github.workspace }}/tests/mock_server.php &

        - name: Run the test suite
          run: make test
          env:
              DB_PORT: ${{ job.services.postgres.ports[5432] }}
